name: calculator
description: A new Flutter project

environment:
  sdk: ">=2.12.0 <3.0.0" # Specify the lower-bound SDK constraint

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
